In [1]:
import numpy as np

In [5]:
from numpy import *
x = array([[1,2,3,4],[5,6,7,8],[10,9,1,2]])
for i in x:
    for j in i:
        print(j,end=" ")
    print()
r = x[0:2,0:2]
print(r)
print("shape :",x.shape)
print("type :",x.dtype)
print("dimension :",x.ndim)
print("size :",x.size)


from numpy import *
x = int(input())
y = int(input())
z = int(input())
arr = ndarray(shape=(x,y,z),dtype=int)
for i in range(x):
    for j in range(y):
        for k in range(z):
            arr[i][j][k]=int(input())
print(arr)

1 2 3 4 
5 6 7 8 
10 9 1 2 
[[1 2]
 [5 6]]
shape : (3, 4)
type : int32
dimension : 2
size : 12
2
2
2
1
1
2
1
2
2
4
4
[[[1 1]
  [2 1]]

 [[2 2]
  [4 4]]]


In [6]:
n

NameError: name 'n' is not defined

In [1]:
import pandas as pd

In [6]:
pd.read_excel("C://Users//Ajay//iris.xls")

ValueError: Excel file format cannot be determined, you must specify an engine manually.